### ISSUE TITLE
Base pair positions incongruences

### ISSUE THREAD

**Issue by mmferrari** [chedinlab/rlooper#5]
Hi,
I have noticed some incongruences about the base pair positions numbering.
I did the following tests:
1. Header: `>test_sequence_template range=HIS3:1-892 5'pad=0 3'pad=0 strand=-`
Base pair positions range in dump file: 0-891
Expected range: 1-892
2. Header: `>test_sequence_template range=HIS3:0-891 5'pad=0 3'pad=0 strand=-`
Base pair positions range in dump file: 1-892
Expected range: 0-891
3. Header: `>test_sequence_nontemplate range=HIS3:1-892 5'pad=0 3'pad=0 strand=+`
Base pair positions range in dump file: 1-892
Expected range: 1-892

Moreover, if I do not specify the coordinates for the sense strand, by default they are 0-891 in the dump file. In contrast, the coordinates are required for the antisense strand (otherwise the program exits with an error).

Could you please clarify this behavior?
Thanks.

**Comment by garden-of-delete** [comment]
I am looking into this and will get back to you.

**Comment by garden-of-delete** [comment]
I have confirmed that there is an issue with potentially incorrect coordinates of the structures output by the dump function. The intended functionality is that the positions of the structures should line up with coordinates in the input file. I will push an updated version of rlooper that addresses this issue along with some other improvements some time next week.

**Comment by garden-of-delete** [comment]
I have fixed two issues issue with the --dump function.
1. The coordinates for the structures output by the dump function are now inclusive of the start and stop coordinate for each structure. This matches how the genome browser treats sequence indices. 
2. Coordinates for each structure output in the dump file were not being adjusted properly for orientation when the strand was specified as '-' in the fasta header. 

You should get your expected behaviour in all cases now. 

You should also always specify a correct coordinate range for your input sequence. Failing to do so may result in unexpected behaviour. I will add more safeguards around that in future updates.

**Comment by mmferrari** [comment]
I have run some tests with the updated version of R-looper and I still have the incongruences described above. Do you have an idea why?
